import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TestComponent } from "../components/test-component";
import { Tabs } from "../components/tabs";
import { InventoryItem } from "../components/InventoryItem";
import { InventoryList } from "../components/InventoryList";
import { Fallbutton } from "../components/fallbutton";

// const suka = {
//   cloneId: 1,
//   cloneName: "Clone #1",
//   cloneImage: "https://i.ibb.co/bQYm5Lv/clone.png",
//   cloneDescription: "ALO ALO ALO ALO ALO ALO ALO ALO ALO ALO ALO ALO",
//   cloneStats: [{ stat1: "25", stat2: "25", stat3: "25" }],
// };
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CLONNING CENTER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://allfont.ru/allfont.css?fonts=a_machinaorto"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://allfont.ru/allfont.css?fonts=a_machinaortosht"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Spartan:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}></main>
      <div className={""}>
        <img
          className={"absolute w-full h-[433.53px] top-[202px]"}
          src={"https://i.ibb.co/34JJDF0/Group-57.png"}
        />
      </div>
      <div className={"absolute left-[893px] top-[592px]"}>
        <Fallbutton width={200} height={50} title={"MINT"}></Fallbutton>
      </div>
      <h2
        className={
          "absolute font-before z-[10] normal text-up text-[104.58px] left-[784px] top-[136px]"
        }
      >
        CLONNING
      </h2>
      <h2
        className={
          "absolute font-before z-[9] font-bold  text-under text-[104.008px] left-[785px] top-[136px]"
        }
      >
        CLONNING
      </h2>
      <h2
        className={
          "absolute font-before z-[10] text-up text-[104.58px] left-[885px] top-[233px]"
        }
      >
        CENTER
      </h2>
      <h2
        className={
          "absolute font-before z-[9] font-bold  text-under text-[104.58px] left-[885px] top-[233px]"
        }
      >
        CENTER
      </h2>
      <p
        className={
          "line-through-[118%] text-align-left absolute font-spartan font-normal text-[26.398px] text-[#E5E5E5] w-[725px] h-[94px ] left-[309px] top-[402px]"
        }
      >
        The only module of the city where order and cleanliness reign. The law
        here is represented by automatic turrets and power grabs for
        trespassers.
      </p>
      <p
        className={
          "line-through-[118%] text-align-left absolute font-spartan font-[600] text-[26.398px] text-[#E5E5E5] w-[565px] h-[56px ] left-[315px] top-[528px]"
        }
      >
        Activate a clone and start conquering the radioactive wasteland
      </p>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
