import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TestComponent } from "../components/test-component";
import { Tabs } from "../components/tabs";
import { InventoryItem } from "../components/InventoryItem";
import { InventoryList } from "../components/InventoryList";
import { Fallbutton } from "../components/fallbutton";

// @ts-ignore
import styled, { keyframes } from "styled-components";
import {
  bounce,
  fadeIn,
  fadeInDown,
  fadeInUp,
  fadeInLeft,
  fadeInDownBig,
} from "react-animations";
// @ts-ignore
import { render } from "react-dom";
import { Navbar } from "../components/Navbar";

const FadeIn = styled.div`
  animation: infinite 2s ${keyframes`${fadeInLeft}`};
  width: 20%;
  position: absolute;
  top: 0;
`;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CLONNING CENTER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://allfont.ru/allfont.css?fonts=a_machinaorto"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://allfont.ru/allfont.css?fonts=a_machinaortosht"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Spartan:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}></main>
      <Navbar></Navbar>
      <div className={""}>
        <img
          className={
            "absolute top-[50px] w-full sm:h-[433.53px] sm:top-[202px]"
          }
          src={"https://i.ibb.co/34JJDF0/Group-57.png"}
        />
      </div>
      <div
        className={
          "absolute left-[10%] right-[10%] w-[80%] top-[50%] sm:w-auto sm:left-[893px] sm:top-[592px]"
        }
      >
        <Fallbutton title={"MINT"}></Fallbutton>
      </div>
      <h2
        className={
          "absolute text-[70px] top-[170px] left-auto w-full text-center font-before z-[10] normal text-up sm:w-auto  sm:text-left sm:text-[104.58px] sm:left-[784px] sm:top-[136px]"
        }
      >
        CLONNING
      </h2>
      <h2
        className={
          "absolute text-[70px] top-[170px] left-auto w-full text-center font-before z-[9] font-bold sm:w-auto  sm:text-left  text-under sm:text-[104.008px] sm:left-[785px] sm:top-[136px]"
        }
      >
        CLONNING
      </h2>

      <div>
        <h2
          className={
            "absolute text-[70px] top-[250px] w-full text-center sm:w-auto sm:text-left left-auto w-full text-center font-before z-[10] text-up sm:text-[104.58px] sm:left-[885px] sm:top-[233px]"
          }
        >
          CENTER
        </h2>
        <h2
          className={
            "absolute text-[70px] top-[250px] w-full text-center sm:w-auto sm:text-left left-auto w-full text-center font-before z-[9] font-bold  text-under sm:text-[104.58px] sm:left-[885px] sm:top-[233px]"
          }
        >
          CENTER
        </h2>
      </div>

      <p
        className={
          "text-center line-through-[118%] w-[90%] left-[5%] right-[5%]  text-[15px] sm:text-left absolute font-spartan font-normal sm:text-[26.398px] text-[#E5E5E5] sm:w-[725px] h-[94px ] sm:left-[309px] top-[402px]"
        }
      >
        The only module of the city where order and cleanliness reign. The law
        here is represented by automatic turrets and power grabs for
        trespassers.
      </p>
      <p
        className={
          "text-center line-through-[118%] w-[90%] left-[5%] right-[5%]  text-[15px] sm:text-left absolute font-spartan font-[600] sm:text-[26.398px] text-[#E5E5E5] sm:w-[565px] h-[56px ] sm:left-[315px] top-[528px]"
        }
      >
        Activate a clone and start conquering the radioactive wasteland
      </p>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
