import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TestComponent } from "../components/test-component";
import { Tabs } from "../components/tabs";
import { InventoryItem } from "../components/InventoryItem";
import { InventoryList } from "../components/InventoryList";

const items = [
  {
    cloneId: 1,
    cloneName: "Clone #1",
    cloneImage: "https://i.ibb.co/bQYm5Lv/clone.png",
    cloneDescription:
      "Some description Some description Some description Some description",
    cloneStats: [{ stat1: "30" }, { stat2: "22" }, { stat3: "111" }],
  },
  {
    cloneId: 2,
    cloneName: "Clone #2",
    cloneImage: "https://i.ibb.co/bQYm5Lv/clone.png",
    cloneDescription:
      "Some description Some description Some description Some description",
    cloneStats: [{ stat1: "30" }, { stat2: "22" }, { stat3: "111" }],
  },
  {
    cloneId: 3,
    cloneName: "Clone #3",
    cloneImage: "https://i.ibb.co/bQYm5Lv/clone.png",
    cloneDescription:
      "Some description Some description Some description Some description",
    cloneStats: [{ stat1: "30" }, { stat2: "22" }, { stat3: "111" }],
  },
  {
    cloneId: 4,
    cloneName: "Clone #4",
    cloneImage: "https://i.ibb.co/bQYm5Lv/clone.png",
    cloneDescription:
      "Some description Some description Some description Some description",
    cloneStats: [{ stat1: "30" }, { stat2: "22" }, { stat3: "111" }],
  },
  {
    cloneId: 5,
    cloneName: "Clone #5",
    cloneImage: "https://i.ibb.co/bQYm5Lv/clone.png",
    cloneDescription:
      "Some description Some description Some description Some description",
    cloneStats: [{ stat1: "30" }, { stat2: "22" }, { stat3: "111" }],
  },
  {
    cloneId: 6,
    cloneName: "Clone #6",
    cloneImage: "https://i.ibb.co/bQYm5Lv/clone.png",
    cloneDescription:
      "Some description Some description Some description Some description",
    cloneStats: [{ stat1: "30" }, { stat2: "22" }, { stat3: "111" }],
  },
  {
    cloneId: 7,
    cloneName: "Clone #7",
    cloneImage: "https://i.ibb.co/bQYm5Lv/clone.png",
    cloneDescription:
      "Some description Some description Some description Some description",
    cloneStats: [{ stat1: "30" }, { stat2: "22" }, { stat3: "111" }],
  },
];
// const suka = {
//   cloneId: 1,
//   cloneName: "Clone #1",
//   cloneImage: "https://i.ibb.co/bQYm5Lv/clone.png",
//   cloneDescription: "ALO ALO ALO ALO ALO ALO ALO ALO ALO ALO ALO ALO",
//   cloneStats: [{ stat1: "25", stat2: "25", stat3: "25" }],
// };
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        {/*<h1 className={"text-red-500"}>*/}
        {/*  Welcome to <a href="https://nextjs.org">Next.js!</a>*/}
        {/*</h1>*/}
        {/*<TestComponent someVar={"ALOOO"}>*/}
        {/*  <p>123546</p>*/}
        {/*</TestComponent>*/}
        {/*<Tabs />*/}
        {/*<p className={styles.description}>*/}
        {/*  Get started by editing{" "}*/}
        {/*  <code className={styles.code}>pages/index.tsx</code>*/}
        {/*</p>*/}

        {/*<div className={styles.grid}>*/}
        {/*  <a href="https://nextjs.org/docs" className={styles.card}>*/}
        {/*    <h2>Documentation &rarr;</h2>*/}
        {/*    <p>Find in-depth information about Next.js features and API.</p>*/}
        {/*  </a>*/}

        {/*  <a href="https://nextjs.org/learn" className={styles.card}>*/}
        {/*    <h2>Learn &rarr;</h2>*/}
        {/*    <p>Learn about Next.js in an interactive course with quizzes!</p>*/}
        {/*  </a>*/}

        {/*  <a*/}
        {/*    href="https://github.com/vercel/next.js/tree/canary/examples"*/}
        {/*    className={styles.card}*/}
        {/*  >*/}
        {/*    <h2>Examples &rarr;</h2>*/}
        {/*    <p>Discover and deploy boilerplate example Next.js projects.</p>*/}
        {/*  </a>*/}

        {/*  <a*/}
        {/*    href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
        {/*    className={styles.card}*/}
        {/*  >*/}
        {/*    <h2>Deploy &rarr;</h2>*/}
        {/*    <p>*/}
        {/*      Instantly deploy your Next.js site to a public URL with Vercel.*/}
        {/*    </p>*/}
        {/*  </a>*/}
        {/*</div>*/}
        <InventoryList list={items} title={"Heroes"}></InventoryList>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
