import type { NextPage } from 'next'
import Head from 'next/head'
import {TestComponent} from "../components/test-component";

const PageIndex: NextPage = () => {
  return (
    <div className={"p-7 "}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"p-7 mt-7 md:p-10 lg:p-16"}>
       <TestComponent someVar={"text!"}/>
      </main>

      <footer className={"p-7"}>

      </footer>
    </div>
  )
}

export default PageIndex
