import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TestComponent } from "../components/test-component";
import { Tabs } from "../components/tabs";
import { InventoryItem } from "../components/InventoryItem";
import { InventoryList } from "../components/InventoryList";

// const suka = {
//   cloneId: 1,
//   cloneName: "Clone #1",
//   cloneImage: "https://i.ibb.co/bQYm5Lv/clone.png",
//   cloneDescription: "ALO ALO ALO ALO ALO ALO ALO ALO ALO ALO ALO ALO",
//   cloneStats: [{ stat1: "25", stat2: "25", stat3: "25" }],
// };
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://allfont.ru/allfont.css?fonts=a_machinaorto"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://allfont.ru/allfont.css?fonts=a_machinaortosht"
          rel="stylesheet"
          type="text/css"
        />
      </Head>

      <main className={styles.main}>
        <div
          className={
            "fixed items-center bg-cover h-[100vh] bg-center bg-no-repeat bg-[url('../public/mobilekpk.png')] sm:bg-[url('../public/pipboy.png')] sm:fixed sm:items-center sm:bg-no-repeat sm:h-[660px] sm:w-[1000px] sm:bg-auto   "
          }
        >
          <div
            className={
              "mt-[100px] ml-auto mr-auto w-[85%]  sm:h-[381px] sm:w-[510px] sm:mr-0 sm:ml-[320px]"
            }
          >
            <Tabs></Tabs>
          </div>
        </div>
        {/*<Tabs></Tabs>*/}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
